#! /usr/bin/perl -w


use FindBin;
use File::Spec;


use constant pristine_tree => "vendor";
use constant patched_tree => "patched";
use constant more_toplevel_excludes => qw/README usr/;


{
   package directory;
   use Carp;
   
   
   sub name {
      return shift->{name};
   }


   sub fail {
      my($me, $msg)= @_;
      croak qq'$msg directory "' . $me->name . qq'": $!';
   }   

   
   sub new {
      my(undef, $name)= @_;
      my $me= bless {};
      local *DIR;
      opendir DIR, $me->{name}= $name or $me->fail("Could not open");
      $me->{dh}= *DIR{IO};
      return $me;
   }
   
   
   DESTROY {
      my $me= shift;
      if (my $dh= $me->{dh}) {
         closedir $dh or $me->fail("Could not close");
      }
   }
   
   
   sub read {
      return readdir shift->{dh};
   }
}


sub ensure_dir($) {
   my($rpath)= @_;
   -d $rpath && return;
   mkdir $rpath or die qq'Could not create directory "$rpath": $!';
   -d $rpath or die $!;
}


sub reconcile_file {
   my($orig, $ovl, $pch)= @_;
   print qq'ORIG "$orig", OVL "$ovl", PATCHED "$pch".\n';
}


sub manage {
   my($basedir, $rpath, $exclusions)= @_;
   my(@d, $entry, $path, $abspath);
   $abspath= File::Spec->catdir($basedir, $rpath);
   {
      my $dh= new directory($abspath);
      while (defined($entry= $dh->read)) {
         next if exists $exclusions->{$entry};
         next unless File::Spec->no_upwards($entry);
         $path= File::Spec->catfile($abspath, $entry);
         if (-f $path) {
            reconcile_file
               map {
                    defined()
                  ? File::Spec->catfile(
                       File::Spec->catdir($basedir, $_, $rpath), $entry
                    )
                  : $path
                  ;
               } pristine_tree, undef, patched_tree
            ;
         } elsif (-d _) {
            push @d, $entry unless $entry =~ /.+\.patches$/;
         }
      }
   }
   foreach $entry (@d) {
      $path= File::Spec->catdir($rpath, $entry);
      foreach (patched_tree, pristine_tree) {
         ensure_dir +File::Spec->catdir($basedir, $_, $path);
      }
      &manage($basedir, $path, $exclusions);
   }
}


my $basedir= $FindBin::Bin;
foreach (pristine_tree, patched_tree) {
   ensure_dir +File::Spec->catdir($basedir, $_);
}
&manage(
     $basedir, File::Spec->curdir
     , {
        map {$_, undef}
          $FindBin::Script, more_toplevel_excludes
        , pristine_tree, patched_tree
     }
);
